# Copyright 2021 The Tekton Authors

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: "2.0"
info:
  title: Chains
  version: 0.0.1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json;q=1
paths:
  /api/v1/entry:
    post:
      summary: Adds an entry
      operationId: addEntry
      tags:
        - entry
      parameters:
        - in: body
          name: query
          required: true
          schema:
            $ref: '#/definitions/Entry'
      responses:
        200:
          description: It worked!
        default:
          $ref: '#/responses/InternalServerError'
  /api/v1/entry/{podName}:
    get:
      summary: Get an entry
      operationId: getEntry
      tags:
        - entry
      parameters:
        - in: path
          name: podName
          type: string
          required: true
          description: name of the pod the workload ran on
      responses:
        200:
          description: A JSON object with the root hash and tree size as properties
          schema:
            $ref: '#/definitions/Entry'
        default:
          $ref: '#/responses/InternalServerError'
definitions:
  Entry:
    type: object
    properties:
      svid:
        type: string
        description: base64 encoded SVID certificate
      signature:
        type: string
        description: base64 encoded SVID signature
      podName:
        type: string
        description: name of the pod the workload ran on
    required:
      - svid
      - signature
      - podName
  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
responses:
  InternalServerError:
    description: There was an internal error in the server while processing the request
    schema:
      $ref: "#/definitions/Error"
